import type { Metadata } from "next";
import "./globals.css";
import { abril, dm_sans, poppins, roboto_slab } from "@/libs/fonts";
import HeaderMain from "@/components/header_main/header_mains";
export const metadata: Metadata = {
  title: "Portfolio Simon-Dev",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${abril.variable} ${dm_sans.variable} ${roboto_slab.variable} relative bg-zinc-900 text-white`}
      >
        {/* <HeaderMain/> */}
        {children}
      </body>
    </html>
  );
}
