name: Keep Render App Awake

on:
  schedule:
    # Cada 10 minutos
    - cron: "*/10 * * * *"
  workflow_dispatch: 

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to app to keep it awake
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://portfolio-o70u.onrender.com/api/health
